train: ../train/images
val: ../valid/images
test: ../test/images

nc: 1
names: ['labubu']

roboflow:
  workspace: polar-robotics-cgvcf
  project: labubu_tracker-0jv6d
  version: 3
  license: CC BY 4.0
  url: https://universe.roboflow.com/polar-robotics-cgvcf/labubu_tracker-0jv6d/dataset/3